/**
 * HeyaAppLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of PostModel
 */
class PostModel extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.createdAt = this.constructor.getValue(obj.createdAt);
        this.updatedAt = this.constructor.getValue(obj.updatedAt);
        this.content = this.constructor.getValue(obj.content);
        this.type = this.constructor.getValue(obj.type);
        this.likes = this.constructor.getValue(obj.likes);
        this.comments = this.constructor.getValue(obj.comments);
        this.user = this.constructor.getValue(obj.user);
        this.medias = this.constructor.getValue(obj.medias);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            {
                name: 'createdAt',
                realName: 'createdAt',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            {
                name: 'updatedAt',
                realName: 'updatedAt',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            { name: 'content', realName: 'content' },
            { name: 'type', realName: 'type' },
            { name: 'likes', realName: 'likes' },
            { name: 'comments', realName: 'comments' },
            { name: 'user', realName: 'user', type: 'UserModel' },
            { name: 'medias', realName: 'medias', array: true, type: 'MediaModel' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = PostModel;
