/**
 * HeyaAppLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Role3Enum = {

    /**
     * TODO: Write general description for this element
     */
    ADMIN: 'ADMIN',

    /**
     * TODO: Write general description for this element
     */
    CLIENT: 'CLIENT',

    /**
     * TODO: Write general description for this element
     */
    PROFESSIONAL: 'PROFESSIONAL',

    /**
     * TODO: Write general description for this element
     */
    USER: 'USER',

};

module.exports = Role3Enum;
