/**
 * HeyaAppLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of UserPaginationModel
 */
class UserPaginationModel extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.itemCount = this.constructor.getValue(obj.itemCount);
        this.totalItems = this.constructor.getValue(obj.totalItems);
        this.pageCount = this.constructor.getValue(obj.pageCount);
        this.next = this.constructor.getValue(obj.next);
        this.previous = this.constructor.getValue(obj.previous);
        this.items = this.constructor.getValue(obj.items);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'itemCount', realName: 'itemCount' },
            { name: 'totalItems', realName: 'totalItems' },
            { name: 'pageCount', realName: 'pageCount' },
            { name: 'next', realName: 'next' },
            { name: 'previous', realName: 'previous' },
            { name: 'items', realName: 'items', array: true, type: 'UserModel' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = UserPaginationModel;
