/**
 * HeyaAppLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of UserModel
 */
class UserModel extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.username = this.constructor.getValue(obj.username);
        this.firstname = this.constructor.getValue(obj.firstname);
        this.lastname = this.constructor.getValue(obj.lastname);
        this.password = this.constructor.getValue(obj.password);
        this.email = this.constructor.getValue(obj.email);
        this.role = this.constructor.getValue(obj.role);
        this.phoneNumber = this.constructor.getValue(obj.phoneNumber);
        this.id = this.constructor.getValue(obj.id);
        this.createdAt = this.constructor.getValue(obj.createdAt);
        this.updatedAt = this.constructor.getValue(obj.updatedAt);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'username', realName: 'username' },
            { name: 'firstname', realName: 'firstname' },
            { name: 'lastname', realName: 'lastname' },
            { name: 'password', realName: 'password' },
            { name: 'email', realName: 'email' },
            { name: 'role', realName: 'role' },
            { name: 'phoneNumber', realName: 'phoneNumber' },
            { name: 'id', realName: 'id' },
            {
                name: 'createdAt',
                realName: 'createdAt',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
            {
                name: 'updatedAt',
                realName: 'updatedAt',
                isDateTime: true,
                dateTimeValue: 'rfc3339',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = UserModel;
