/**
 * HeyaAppLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const UserModel = require('../lib/Models/UserModel');
const UserPaginationModel = require('../lib/Models/UserPaginationModel');
const UserCreateModel = require('../lib/Models/UserCreateModel');
const UserUpdateModel = require('../lib/Models/UserUpdateModel');
const UserUpdatePasswordModel = require('../lib/Models/UserUpdatePasswordModel');
const MediaModel = require('../lib/Models/MediaModel');
const PostModel = require('../lib/Models/PostModel');
const PostPaginationModel = require('../lib/Models/PostPaginationModel');
const PostCreateModel = require('../lib/Models/PostCreateModel');
const PostRegisterModel = require('../lib/Models/PostRegisterModel');
const PostCommentCreateModel = require('../lib/Models/PostCommentCreateModel');
const PostCommentUpdateModel = require('../lib/Models/PostCommentUpdateModel');
const MediaResource = require('../lib/Models/MediaResource');
const PostLikes = require('../lib/Models/PostLikes');
const Post = require('../lib/Models/Post');
const PostComment = require('../lib/Models/PostComment');
const Follows = require('../lib/Models/Follows');
const User = require('../lib/Models/User');
const PostCommentModel = require('../lib/Models/PostCommentModel');
const CommentsPaginationModel = require('../lib/Models/CommentsPaginationModel');
const LoginUserModel = require('../lib/Models/LoginUserModel');
const LoginResponseModel = require('../lib/Models/LoginResponseModel');
const CreateUserDto = require('../lib/Models/CreateUserDto');
const ErrorResponseException = require('../lib/Exceptions/ErrorResponseException');

const classMap = {
    UserModel,
    UserPaginationModel,
    UserCreateModel,
    UserUpdateModel,
    UserUpdatePasswordModel,
    MediaModel,
    PostModel,
    PostPaginationModel,
    PostCreateModel,
    PostRegisterModel,
    PostCommentCreateModel,
    PostCommentUpdateModel,
    MediaResource,
    PostLikes,
    Post,
    PostComment,
    Follows,
    User,
    PostCommentModel,
    CommentsPaginationModel,
    LoginUserModel,
    LoginResponseModel,
    CreateUserDto,
    ErrorResponseException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
